### ISSUE TITLE
Editing some keys will affect the same key in different layers.

### ISSUE THREAD

**Issue by nsicoco** [hidergo/BoardPilot#2]
Example steps to reproduce:

1. On the Default layer, set the topleft most key (the `Escape` key) to `A`
2. Switch to the Arrow layer, set the same key to `B` on the Arrow layer
3. Switch back to the Default layer. The same key has reset to the default (`Escape`)
4. On the Default layer, set the same key back to `A` again
5. Switch back to the Arrow layer. The same key is now set to `Transparent`

This is reproducible on several keys on all 3 layers.

**Comment by ilp0** [comment]
This is fixed in 1.0.1, thanks for the report!
