### ISSUE TITLE
No connection under Manjaro

### ISSUE THREAD

**Issue by YigsLittlePig** [hidergo/BoardPilot#4]
Board Pilot gives 'No devices available or background service is not running' message in the top right. 'board-pilot' and 'BoardPilotService' are both running under processes, my user has been added to the appropriate group and the computer rebooted, same result running as root.

**Comment by YigsLittlePig** [comment]
Update: I downloaded the 1.0.1 release this morning and it's working under root now and actually outputting some logs and it looks like this is probably some kind of issue with my audio set up that simply has not presented itself until now.

**Comment by ilp0** [comment]
Alright, I'm glad you got it sorted out. The 1.0.1 update doesnt have changes that would affect this I dont think, maybe just reinstallation of the software fixed it. Closing as resolved.
